
default_platform(:android)

platform :android do
    desc "lane for Android firebase app distribution"
    lane :firebase_distribution do
        sh "flutter clean"
        sh "flutter build apk --release --flavor production --target lib/main.dart --no-tree-shake-icons"
        firebase_app_distribution(
            app: ENV["FIREBASE_KEY"],
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "C:/Users/moume/StudioProjects/doctor_app/build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "moumen5733k@gmail.com",
            release_notes: "first fastlane firebase distribution"
        )
    end
end